export const DEEP_EN = {
  'deep.item.pointyHat': 'Pointy Hat',
  'deep.item.pointyHat.perk': 'Never breaks. Mostly decorative.',
  'deep.item.manaWard': 'Mana Ward',
  'deep.item.manaWard.perk': 'Light magic bubble: easier parries.',
  'deep.item.runeWard': 'Rune Ward',
  'deep.item.runeWard.perk': 'Solid all-round spell.',
  'deep.item.arcaneBarrier': 'Arcane Barrier',
  'deep.item.arcaneBarrier.perk': 'Absorbs a lot, but parries are harder.',
  'deep.item.firewall': 'Firewall of the Sysadmin',
  'deep.item.firewall.perk': 'Epic. Blocks everything except the boss.',
  'deep.foe.glitch': 'Glitch',
  'deep.killer.glitch': 'a glitch',
  'deep.manager.euh': 'Euh, {name}…',
  'deep.manager.doliprane': 'Anyone got a Doliprane?',
  'deep.float.coffeeOrder': "I'll have the special…",
  'deep.loot.swapSub': 'leave yours here',
  'deep.tip.glitch.eyebrow': 'Glitch',
  'deep.tip.glitch.title': 'Static on the line',
  'deep.tip.glitch.text': 'Glitches make the strike meter crackle and jitter. The gold zone does not move: keep your timing.',
  'deep.tip.glitch.short': 'The meter crackles. The gold zone stays put.',
  'deep.float.hits': '{n} HITS',
  'deep.title': 'THE DEEP DUNGEON',
  'deep.subtitle': 'No respawns. No second chances.',
  'deep.create.eyebrow': 'The Deep Dungeon',
  'deep.create.step.cls': 'Class',
  'deep.create.step.weapon': 'Weapon',
  'deep.create.step.shield': 'Shield',
  'deep.create.step.name': 'Hero',
  'deep.create.title.cls': 'Choose your class',
  'deep.create.title.weapon': 'Choose your weapon',
  'deep.create.title.shield': 'Choose your shield',
  'deep.create.title.name': 'Meet your hero',
  'deep.create.reroll': '🎲 New name',
  'deep.create.rerollAgain': '🎲 Still not happy?',
  'deep.create.rerollAll': "🎲 They're ALL great names",
  'deep.create.rerollLabel': 'Roll a new random name',
  'deep.create.back': '◂ Back',
  'deep.create.next': 'Next ▸',
  'deep.create.enter': 'Enter the dungeon ▸',
  'deep.create.note': 'Weapons and shields wear out. Your Wooden Stick and Pot Lid never do.',
  'deep.class.knight': 'Knight',
  'deep.class.rogue': 'Rogue',
  'deep.class.wizard': 'Wizard',
  'deep.class.barbarian': 'Barbarian',
  'deep.class.knight.perk': 'Steady guard: easier parries.',
  'deep.class.rogue.perk': 'Precision: bigger gold zone, perfect hits ×4.',
  'deep.class.wizard.perk': 'Time magic: the strike marker moves slower. Casts spells.',
  'deep.class.barbarian.perk': 'Rage: +3 ATK below 40% HP. Blocks less.',
  'deep.stat.hp': 'HP',
  'deep.stat.atk': 'ATK',
  'deep.stat.guard': 'GUARD',
  'deep.stat.focus': 'FOCUS',
  'deep.stat.power': 'POWER',
  'deep.stat.uses': 'USES',
  'deep.stat.absorb': 'ABSORB',
  'deep.stat.parry': 'PARRY',
  'deep.item.stick': 'Wooden Stick',
  'deep.item.stick.perk': 'Never breaks. Never impresses.',
  'deep.item.sword': 'Sword',
  'deep.item.sword.perk': 'Balanced.',
  'deep.item.axe': 'War Axe',
  'deep.item.axe.perk': 'Hits hard, wears fast.',
  'deep.item.daggers': 'Twin Daggers',
  'deep.item.daggers.perk': 'Perfect streaks build combos twice as fast. Lasts long.',
  'deep.item.oakStaff': 'Oak Staff',
  'deep.item.oakStaff.perk': 'Balanced magic bolts.',
  'deep.item.emberStaff': 'Ember Staff',
  'deep.item.emberStaff.perk': 'Burns hard, burns out fast.',
  'deep.item.stormStaff': 'Storm Staff',
  'deep.item.stormStaff.perk': 'Perfect streaks build combos twice as fast. Lasts long.',
  'deep.item.morningStar': 'Morning Star',
  'deep.item.morningStar.perk': 'Spiky. Very much a morning person.',
  'deep.item.runeStaff': 'Rune Staff',
  'deep.item.runeStaff.perk': 'Crackles with old magic.',
  'deep.item.spear': 'Spear',
  'deep.item.spear.perk': 'Long reach, long life.',
  'deep.item.wand': 'Crystal Wand',
  'deep.item.wand.perk': 'Light, sturdy, sparkly.',
  'deep.item.lightbringer': 'Lightbringer',
  'deep.item.lightbringer.perk': 'Legendary. Glows. Hums. Probably fine.',
  'deep.item.sunStaff': 'Staff of the Sun',
  'deep.item.sunStaff.perk': 'Legendary. Warm to the touch. Very warm.',
  'deep.item.potLid': 'Pot Lid',
  'deep.item.potLid.perk': 'Never breaks. Barely blocks.',
  'deep.item.buckler': 'Buckler',
  'deep.item.buckler.perk': 'Small and light: easier parries.',
  'deep.item.kite': 'Kite Shield',
  'deep.item.kite.perk': 'Solid all-rounder.',
  'deep.item.tower': 'Tower Shield',
  'deep.item.tower.perk': 'Absorbs a lot, but parries are harder.',
  'deep.item.aegis': 'Aegis of the Sysadmin',
  'deep.item.aegis.perk': 'Epic. Uptime 99.99%.',
  'deep.item.small': 'Small Potion',
  'deep.item.small.perk': 'Tastes like cherries.',
  'deep.item.large': 'Large Potion',
  'deep.item.large.perk': 'Tastes like cherries and courage.',
  'deep.item.cola': 'Cherry Coke',
  'deep.item.cola.perk': "Ezra's favourite. Heals a lot.",
  'deep.room.den': "Ezra's Den",
  'deep.room.den.line': 'A couch, a Game Boy, a sleeping cat. Nobody is supposed to know about this room.',
  'deep.line.secret': 'Secret room',
  'deep.nav.portal': 'Step into the portal',
  'deep.nav.portalTo': 'To: {room}',
  'deep.nav.pet': 'Pet the cat',
  'deep.nav.petDetail': '+{heal} HP · purr',
  'deep.float.secret': 'SECRET ROOM! +{points}',
  'deep.float.purr': 'Purrr…',
  'deep.fairy.room.den': "Ezra's den! He hides here when the build is red.",
  'deep.item.keycard': "Manager's Keycard",
  'deep.item.keycard.perk': 'Opens the iron door.',
  'deep.noPotion': 'No potion',
  'deep.map': 'Dungeon map',
  'deep.room.unknown': 'Unexplored',
  'deep.room.street': 'Main Street',
  'deep.room.h1': 'Main Street · Gate',
  'deep.room.h2': 'Main Street · Arrow Alley',
  'deep.room.h3': 'Main Street · Crossing',
  'deep.room.h4': 'Main Street · Iron Door',
  'deep.room.a1': 'The Archives',
  'deep.room.a2': 'The Open Space',
  'deep.room.mb': "The Manager's Office",
  'deep.room.b1': 'The Server Room',
  'deep.room.c1': 'The Break Room',
  'deep.room.d1': 'The Descent',
  'deep.room.d2': 'The Flooded Crypt',
  'deep.room.d3': 'The Hall of Echoes',
  'deep.room.lair': 'The Light',
  'deep.room.h1.line': 'A long street of doors. It smells like old code.',
  'deep.room.h2.line': 'The walls have holes. The holes have arrows.',
  'deep.room.h3.line': 'One door hums with a vending-machine glow.',
  'deep.room.h4.line': 'The end of the street. An iron door with a card reader.',
  'deep.room.a1.line': 'Dusty shelves. Nobody reads the docs.',
  'deep.room.a2.line': 'Desks, plants, one very loud keyboard.',
  'deep.room.mb.line': 'Motivational poster. Big desk. Bigger ego.',
  'deep.room.b1.line': 'Blinking lights and a hum you feel in your teeth.',
  'deep.room.c1.line': 'Vending machines. A coffee machine. A suspiciously shiny chest.',
  'deep.room.d1.line': 'Chains on the walls. The air gets colder.',
  'deep.room.d2.line': 'Knee-deep water. Something drips. Something waits.',
  'deep.room.d3.line': 'Purple fire and pillars. Your footsteps answer back.',
  'deep.room.lair.line': 'A single light bulb, swinging.',
  'deep.detail.weapon': '+{power} ATK · {uses}/{max} uses',
  'deep.detail.shield': 'Absorbs {absorb}% · holds {uses}/{max} attacks',
  'deep.offline': 'Offline: this run will not be saved',
  'deep.detail.potion': '+{heal} HP',
  'deep.detail.potionCure': '+{heal} HP · cures the poison',
  'deep.float.cured': 'CURED!',
  'deep.fairy.poisoned': 'Venom! It burns more and more often. Any potion cures it.',
  'deep.fairy.poisoned.cryptic': 'Venom.',
  'deep.nav.eyebrow': 'Where to?',
  'deep.nav.moveOn': 'Move on ▸',
  'deep.nav.goBack': '◂ Go back',
  'deep.nav.cleared': 'Already cleared',
  'deep.nav.unexplored': 'Unexplored',
  'deep.nav.enterDoor': 'Enter the door',
  'deep.nav.exitDoor': 'Back to the street',
  'deep.nav.goOn': 'Go on ▸',
  'deep.nav.backTo': '◂ Back to',
  'deep.nav.noReturn': 'No way back',
  'deep.nav.open': 'Open the glowing chest',
  'deep.nav.openDetail': 'What could go wrong?',
  'deep.nav.coffee': 'Coffee break',
  'deep.nav.coffeeDetail': '+{heal} HP · once',
  'deep.nav.take': 'Pick up: {item}',
  'deep.nav.bagFull': 'Bag full ({max} potions max)',
  'deep.nav.drink': 'Drink: {potion}',
  'deep.nav.locked': 'Iron door (locked)',
  'deep.nav.needKeycard': "Needs the manager's keycard",
  'deep.fairy.helloFriend': "Psst… {name}! I'm Lumi. You were nice to me, so I'll whisper tips along the way.",
  'deep.fairy.helloSulky': "Oh. It's you. The one who said no. …Fine. Follow me.",
  'deep.fairy.friend.h1': 'Tip: explore everything. Some dead ends are worth it.',
  'deep.fairy.friend.a1': 'Remember this room. Come back after the manager… things shimmer here.',
  'deep.fairy.friend.mb': 'He always goes: padlock, sticky notes, the big hmpf, then the meeting. Parry the hmpf!',
  'deep.fairy.friend.h4': 'The manager has the keycard. Once you have it, the archives hide a shortcut.',
  'deep.fairy.friend.d2': 'Five arrows here, and two of them come in pairs.',
  'deep.fairy.friend.d3': 'That chest in here bites. Hit it clean.',
  'deep.fairy.friend.den': "Ezra's den! Pet the cat, trust me.",
  'deep.fairy.friend.drink': 'You look terrible. Drink something!',
  'deep.fairy.friend.lastRoom': 'The last room is ahead. Drink up before you go in… trust me.',
  'deep.fairy.friend.portal': 'Psst… the air shimmers here now. A portal!',
  'deep.fairy.idle': 'Zzz… oh! Still deciding?',
  'deep.fairy.locked': "Locked. That reader wants the manager's keycard.",
  'deep.fairy.bagFull': 'Your bag is full. Drink one first?',
  'deep.fairy.keycard': 'The keycard! Now, that iron door…',
  'deep.fairy.worn': "Psst… {item}: only a few hits left. Perfect hits don't wear it.",
  'deep.fairy.worn.hard': 'Psst… {item}: only a few hits left. Know where the next one is.',
  'deep.fairy.brokeWeapon': 'Broken! Back to the trusty stick. That one never breaks.',
  'deep.fairy.brokeShield': 'Shield gone! The pot lid will do… sort of.',
  'deep.fairy.loot': "Tip: leave it here if yours still holds. Nothing respawns, you can come back for it.",
  'deep.fairy.hordeDone': 'You survived THAT? …I mean, yay! Have a coffee.',
  'deep.fairy.reveal1': 'Psst… thanks for the keycard.',
  'deep.fairy.reveal2': 'Did you really think I was a fairy?',
  'deep.fairy.room.a1': 'The archives. Nobody has read these since 2009.',
  'deep.fairy.room.a2': "The open space. Shh, someone's on a call.",
  'deep.fairy.room.mb': "Uh oh. The manager's office.",
  'deep.fairy.room.b1': 'The server room… if you only knew what happened in here…',
  'deep.fairy.room.c1': 'Ooh, a glowing chest! Open it, open it!',
  'deep.fairy.room.h3': 'A giant. Hit clean, your blade will thank you.',
  'deep.fairy.room.h4': 'That iron door needs a keycard. The manager always keeps his on him.',
  'deep.fairy.room.d1': 'Deeper we go. I love the dark.',
  'deep.fairy.room.d2': 'Watch the walls. And your feet.',
  'deep.fairy.room.d3': 'Almost there… the light is so close.',
  'deep.tip.nav.eyebrow': 'Explore',
  'deep.tip.nav.title': 'You choose the way',
  'deep.tip.nav.text': "Doors lead to rooms. Cleared rooms stay cleared, and anything you leave on the floor stays there. Plan your route: the map shows where you've been.",
  'deep.tip.nav.short': 'Pick a door or move on.',
  'deep.tip.strike.eyebrow': 'Attack',
  'deep.tip.strike.title': 'Perfect hits are harder here',
  'deep.tip.strike.text': "The gold zone is tiny. Perfect hits deal triple damage AND don't wear your weapon. Weak hits wear it twice as fast.",
  'deep.tip.strike.short': 'Gold = perfect, no wear.',
  'deep.tip.strike.text.hard': 'The gold zone is tiny and moves faster. Perfect hits deal triple damage. On Difficult every hit wears your weapon, weak ones three times as much.',
  'deep.tip.strike.short.hard': 'Gold = perfect. Everything wears.',
  'deep.tip.strike.text.tryhard': 'The gold zone is tiny. Perfect hits deal triple damage. On Try Hard EVERY hit wears your weapon, weak ones three times as much. It will break: know where the next one is.',
  'deep.tip.defend.eyebrow': 'Defend',
  'deep.tip.defend.title': 'One ring = one hit',
  'deep.tip.defend.text': 'Each ring closes on you and is one hit. Tap once per ring, right when it touches the white circle: PARRY = no damage and your next strike ×1.5. A bit off = BLOCK, your guard absorbs part of it. Three rings? Three taps, one for each.',
  'deep.tip.defend.short': 'One tap per ring, when it touches you.',
  'deep.tip.defend.text.hard': 'Each ring closes on you and is one hit. Tap once per ring, right when it touches the white circle: PARRY = no damage and your next strike ×1.5. A bit off = BLOCK. On Difficult the rings fade as they get close: feel the rhythm.',
  'deep.tip.defend.short.hard': 'The rings fade near you. Keep the rhythm.',
  'deep.tip.defend.text.tryhard': 'Each ring closes on you and is one hit. Tap once per ring as it touches the white circle: PARRY or BLOCK. On Try Hard the rings vanish right before they hit. Count the beat.',
  'deep.tip.armor.eyebrow': 'Armor',
  'deep.tip.armor.title': 'This one is armored',
  'deep.tip.armor.text': 'Armor shaves damage off every hit. Weak blows barely scratch it: aim for gold.',
  'deep.tip.armor.short': 'Armored: aim for gold.',
  'deep.tip.ghost.eyebrow': 'Ghost',
  'deep.tip.ghost.title': 'Now you see it…',
  'deep.tip.ghost.text': 'Ghosts make the marker fade in and out. Trust your rhythm.',
  'deep.tip.ghost.short': 'The marker fades. Keep the rhythm.',
  'deep.tip.arrows.eyebrow': 'Trap',
  'deep.tip.arrows.title': 'Wall arrows!',
  'deep.tip.arrows.text': 'Arrows shoot out of the wall. Tap to jump right when an arrow reaches you. Each one that hits costs {damage} HP.',
  'deep.tip.arrows.short': 'Tap to jump the arrows.',
  'deep.tip.horde.eyebrow': 'Horde',
  'deep.tip.horde.title': 'Fifteen of them',
  'deep.tip.horde.text': 'They come from both sides, faster and faster. Tap on each beat as they reach you. Mashing makes you flail and miss.',
  'deep.tip.horde.short': 'Tap each one on the beat!',
  'deep.float.explore': 'NEW ROOM +{points}',
  'deep.float.elite': 'ELITE {name}!',
  'deep.float.riposte': 'RIPOSTE ×1.5',
  'deep.float.broke': 'CRACK! {item}',
  'deep.float.parry': 'PARRY!',
  'deep.float.block': 'BLOCK',
  'deep.float.jump': 'DODGED',
  'deep.float.jumpPerfect': 'CLEAN DODGE!',
  'deep.float.slash': 'SLASH',
  'deep.float.slashPerfect': 'PERFECT!',
  'deep.float.flail': 'FLAILING!',
  'deep.float.dusted': 'DUSTED! Next marker faster',
  'deep.float.keycard': 'KEYCARD!',
  'deep.float.itsATrap': "IT'S A TRAP!",
  'deep.float.hordeClear': 'HORDE CLEARED! ({n})',
  'deep.float.hordePerfect': 'PERFECT RHYTHM!',
  'deep.float.untouched': 'UNTOUCHED!',
  'deep.float.melon': 'WATERMELON MODE!',
  'deep.float.managerDown': 'MEETING ADJOURNED',
  'deep.float.dropped': 'Dropped: {item}',
  'deep.float.left': 'Left here: {item}',
  'deep.float.coffee': "Aah, that's good.",
  'deep.announce.foe': '{name} appears with {hp} HP.',
  'deep.foe.rat': 'Rat',
  'deep.foe.bat': 'Bat',
  'deep.foe.slime': 'Slime',
  'deep.foe.spider': 'Giant Spider',
  'deep.foe.ghost': 'Ghost',
  'deep.foe.giant': 'Giant',
  'deep.foe.crab': 'Crab Demon',
  'deep.foe.monk': 'Dark Monk',
  'deep.foe.knight': 'Dark Knight',
  'deep.foe.mimic': 'Mimic',
  'deep.foe.bug': 'Bug',
  'deep.foe.manager': 'THE GRUMPY MANAGER',
  'deep.foe.manager.title': 'Has a meeting about this',
  'deep.foe.moth': 'THE FIRST BUG',
  'deep.foe.moth.title': 'Harvard Mark II · 9 Sept 1947',
  'deep.hint.arrows': 'Tap to jump!',
  'deep.hint.horde': 'Tap on each beat!',
  'deep.horde.title': 'HORDE!',
  'deep.horde.subtitle': 'The doors are locked',
  'deep.potion.drink': '{potion} (+{heal})',
  'deep.tier.basic': 'Basic',
  'deep.tier.common': 'Common',
  'deep.tier.rare': 'Rare',
  'deep.tier.epic': 'Epic',
  'deep.tier.legendary': 'Legendary',
  'deep.loot.vsWeapon': 'You hold: {item} · {detail}',
  'deep.loot.vsShield': 'You carry: {item} · {detail}',
  'deep.loot.bag': 'Bag: {n}/{max} potions',
  'deep.loot.takePotion': 'Take it',
  'deep.loot.swap': 'Swap',
  'deep.loot.take': 'Take it',
  'deep.loot.leave': 'Leave it here',
  'deep.loot.note': 'Left items stay on this floor. Come back any time.',
  'deep.manager.speaker': 'THE MANAGER',
  'deep.manager.offstage': 'A VOICE, SOMEWHERE',
  'deep.powerCut': 'POWER CUT!',
  'deep.fairy.powerCut': "Who turned off the lights?! Watch the rings, they still glow.",
  'deep.manager.intro': '{name}, quick sync?',
  'deep.manager.lock': 'Lock your computer!',
  'deep.manager.lastpass': 'All passwords in LastPass!',
  'deep.manager.meeting': 'Lots of meetings. With everyone.',
  'deep.manager.seeds': 'Seeds of doubt!',
  'deep.manager.melon': 'My head is like a watermelon!',
  'deep.moth.speaker': 'THE FIRST BUG',
  'deep.moth.intro': 'In 1947 they taped me into a logbook. Tonight, I debug YOU.',
  'deep.moth.dust': 'Dust in your eyes!',
  'deep.moth.spawn': 'Fix one bug… get two more!',
  'deep.moth.back': 'Did you miss me?',
  'deep.moth.frenzy': 'It works on MY machine!',
  'deep.logbook.aria': 'The logbook page with the moth taped to it: first actual case of bug being found.',
  'deep.logbook.title': 'Bug fixed.',
  'deep.killer.rat': 'a rat',
  'deep.killer.bat': 'a bat',
  'deep.killer.slime': 'a slime',
  'deep.killer.spider': 'a giant spider',
  'deep.killer.ghost': 'a ghost',
  'deep.killer.giant': 'a giant',
  'deep.killer.crab': 'a crab demon',
  'deep.killer.monk': 'a dark monk',
  'deep.killer.knight': 'a dark knight',
  'deep.killer.mimic': 'a mimic',
  'deep.killer.bug': 'a bug',
  'deep.killer.manager': 'the grumpy manager',
  'deep.killer.moth': 'the first bug',
  'deep.killer.horde': 'the horde',
  'deep.killer.arrow': 'a wall arrow',
  'deep.killer.poison': 'spider venom',
  'deep.killer.dungeon': 'the dungeon',
  'deep.results.won': 'BUG FIXED',
  'deep.results.wonLine': '{name} conquered the Deep Dungeon.',
  'deep.results.lostLine': '{name} was taken down by {killer} in {room}.',
  'deep.results.again': 'New hero',
  'deep.results.offline': "Offline: your {score} points weren't saved.",
  'deep.results.rankLine': "You'd be {rank} on the wall of legends. Try again to carve your name in it!",
  'deep.results.qualified': 'Your score fits on the wall of legends!',
  'deep.results.carved': '{initials} is carved into the wall of legends!',
  'deep.line.strikes': 'Strikes',
  'deep.line.combos': 'Perfect combos',
  'deep.line.defense': 'Parries & blocks',
  'deep.line.dodges': 'Dodges',
  'deep.line.horde': 'Horde',
  'deep.line.kills': 'Kills',
  'deep.line.flawless': 'Flawless rooms',
  'deep.line.explore': 'Exploration',
  'deep.line.hp': 'HP left',
  'deep.line.time': 'Time bonus',
  'deep.wall': 'The wall of legends',
  'deep.secretLegend': 'found the secret passage',
  'deep.results.replay': 'Play again with this hero',
  'deep.logbook.skip': 'Click or press any key',
  'deep.create.step.difficulty': 'Level',
  'deep.create.title.difficulty': 'Choose your challenge',
  'deep.difficulty.normal': 'Normal',
  'deep.difficulty.hard': 'Difficult',
  'deep.difficulty.tryhard': 'Try Hard',
  'deep.difficulty.normal.perk': 'The dungeon as it was built. It still bites.',
  'deep.difficulty.hard.perk': 'Foes toughen the deeper you go, bosses hit hard, potions heal less and every hit wears your weapon.',
  'deep.difficulty.tryhard.perk': 'Your gear WILL break, the bag holds 2 potions, Lumi barely talks. Plan your way back.',
  'deep.difficulty.normal.short': 'Normal',
  'deep.difficulty.hard.short': 'Difficult',
  'deep.difficulty.tryhard.short': 'Try Hard',
  'deep.stat.foes': 'Foes',
  'deep.stat.bag': 'Bag',
  'deep.stat.score': 'Score',
  'deep.line.difficulty': 'Difficulty bonus',
  'deep.fairy.helloTryhard': 'Try Hard? Bold. You are on your own, {name}.',
  'deep.fairy.room.a1.cryptic': 'Dust. And something else.',
  'deep.fairy.room.mb.cryptic': 'Him.',
  'deep.fairy.room.b1.cryptic': 'Bzzt.',
  'deep.fairy.room.c1.cryptic': 'Shiny…',
  'deep.fairy.room.h4.cryptic': 'Iron.',
  'deep.fairy.room.d2.cryptic': 'The walls have eyes.',
  'deep.fairy.room.d3.cryptic': 'Close.',
  'deep.fairy.room.den.cryptic': 'Shh.',
  'deep.fairy.powerCut.cryptic': 'Dark.',
  'deep.fairy.idle.cryptic': '…',
  'deep.fairy.locked.cryptic': 'Locked.',
  'deep.fairy.bagFull.cryptic': 'Full.',
  'deep.fairy.keycard.cryptic': 'Hm. Useful.',
  'deep.fairy.worn.cryptic': 'Creak…',
  'deep.fairy.brokeWeapon.cryptic': 'Snap.',
  'deep.fairy.brokeShield.cryptic': 'Crack.',
  'deep.fairy.hordeDone.cryptic': 'Huh.',
  'deep.challenge': "Can you beat {who}'s {score} in the Deep Dungeon? Ask the fairy.",
  'deep.wallEmpty': 'No legend yet. The fairy knows the way.',
  'deep.share.top': "{initials} is on the Deep Dungeon's wall of legends with {score} pts. Your turn: {url}",
  'deep.share.win': 'I beat the Deep Dungeon with {score} pts. Can you? {url}',
  'deep.share.death': 'The Deep Dungeon got me at {score} pts. Can you go deeper? {url}',
  'fairy.psst': 'psst!',
  'fairy.question': 'Psst… how about a REAL dungeon now?',
  'fairy.yes': 'Yes!',
  'fairy.no': 'No',
  'fairy.yesLine': 'Follow me!',
  'fairy.sad': '…fine.',
  'fairy.label': 'Talk to the fairy',
  'fairy.questionFriend': 'Psst… you again! Another REAL dungeon?',
  'fairy.questionSulky': 'Hmpf. You said no last time. …Want a REAL dungeon now?',
  'fairy.legends': '🏆 The wall of legends',
  'fairy.legendsLine': 'Only the ones who made it out get carved here.',
  'fairy.back': '◂ Back',
  'fairy.konami': '+30 lives? Not in THIS dungeon.',
  'fairy.name': 'You know my name?! …Nobody ever says my name.',
};

export const DEEP_FR = {
  'deep.item.pointyHat': 'Chapeau pointu',
  'deep.item.pointyHat.perk': 'Ne casse jamais. Surtout décoratif.',
  'deep.item.manaWard': 'Bouclier de mana',
  'deep.item.manaWard.perk': 'Bulle magique légère : parades plus faciles.',
  'deep.item.runeWard': 'Sceau runique',
  'deep.item.runeWard.perk': 'Sort polyvalent et solide.',
  'deep.item.arcaneBarrier': 'Barrière arcanique',
  'deep.item.arcaneBarrier.perk': 'Absorbe beaucoup, mais parer est plus dur.',
  'deep.item.firewall': 'Pare-feu de l’Admin Sys',
  'deep.item.firewall.perk': 'Épique. Bloque tout, sauf le boss.',
  'deep.foe.glitch': 'Glitch',
  'deep.killer.glitch': 'un glitch',
  'deep.manager.euh': 'Euh, {name}…',
  'deep.manager.doliprane': 'Quelqu’un a un doliprane ?',
  'deep.float.coffeeOrder': 'Je prends le spécial…',
  'deep.loot.swapSub': 'laisse le tien ici',
  'deep.tip.glitch.eyebrow': 'Glitch',
  'deep.tip.glitch.title': 'De la friture sur la ligne',
  'deep.tip.glitch.text': 'Les glitchs font grésiller et trembler la jauge. La zone dorée ne bouge pas : garde ton rythme.',
  'deep.tip.glitch.short': 'La jauge grésille. La zone dorée ne bouge pas.',
  'deep.float.hits': '{n} COUPS',
  'deep.title': 'LE DONJON DES PROFONDEURS',
  'deep.subtitle': 'Pas de respawn. Pas de seconde chance.',
  'deep.create.eyebrow': 'Le Donjon des Profondeurs',
  'deep.create.step.cls': 'Classe',
  'deep.create.step.weapon': 'Arme',
  'deep.create.step.shield': 'Bouclier',
  'deep.create.step.name': 'Héros',
  'deep.create.title.cls': 'Choisis ta classe',
  'deep.create.title.weapon': 'Choisis ton arme',
  'deep.create.title.shield': 'Choisis ton bouclier',
  'deep.create.title.name': 'Voici ton héros',
  'deep.create.reroll': '🎲 Autre nom',
  'deep.create.rerollAgain': '🎲 Toujours pas ?',
  'deep.create.rerollAll': '🎲 Ils sont TOUS très bien',
  'deep.create.rerollLabel': 'Tirer un autre nom au hasard',
  'deep.create.back': '◂ Retour',
  'deep.create.next': 'Suivant ▸',
  'deep.create.enter': 'Entrer dans le donjon ▸',
  'deep.create.note': "Armes et boucliers s'usent. Ton bâton et ton couvercle, jamais.",
  'deep.class.knight': 'Chevalier',
  'deep.class.rogue': 'Voleur',
  'deep.class.wizard': 'Magicien',
  'deep.class.barbarian': 'Barbare',
  'deep.class.knight.perk': 'Garde solide : parades plus faciles.',
  'deep.class.rogue.perk': 'Précision : zone dorée plus large, coups parfaits ×4.',
  'deep.class.wizard.perk': 'Magie du temps : le curseur ralentit. Lance des sorts.',
  'deep.class.barbarian.perk': 'Rage : +3 ATQ sous 40 % de PV. Bloque moins bien.',
  'deep.stat.hp': 'PV',
  'deep.stat.atk': 'ATQ',
  'deep.stat.guard': 'GARDE',
  'deep.stat.focus': 'PRÉCISION',
  'deep.stat.power': 'PUISSANCE',
  'deep.stat.uses': 'USAGE',
  'deep.stat.absorb': 'ABSORPTION',
  'deep.stat.parry': 'PARADE',
  'deep.item.stick': 'Bâton en bois',
  'deep.item.stick.perk': "Ne casse jamais. N'impressionne jamais.",
  'deep.item.sword': 'Épée',
  'deep.item.sword.perk': 'Équilibrée.',
  'deep.item.axe': 'Hache de guerre',
  'deep.item.axe.perk': "Frappe fort, s'use vite.",
  'deep.item.daggers': 'Dagues jumelles',
  'deep.item.daggers.perk': 'Les séries parfaites montent le combo deux fois plus vite. Durables.',
  'deep.item.oakStaff': 'Bâton de chêne',
  'deep.item.oakStaff.perk': 'Éclairs magiques équilibrés.',
  'deep.item.emberStaff': 'Bâton de braise',
  'deep.item.emberStaff.perk': "Brûle fort, s'épuise vite.",
  'deep.item.stormStaff': 'Bâton des tempêtes',
  'deep.item.stormStaff.perk': 'Les séries parfaites montent le combo deux fois plus vite. Durable.',
  'deep.item.morningStar': 'Étoile du matin',
  'deep.item.morningStar.perk': 'Hérissée. Très du matin.',
  'deep.item.runeStaff': 'Bâton runique',
  'deep.item.runeStaff.perk': 'Crépite de vieille magie.',
  'deep.item.spear': 'Lance',
  'deep.item.spear.perk': 'Longue portée, longue vie.',
  'deep.item.wand': 'Baguette de cristal',
  'deep.item.wand.perk': 'Légère, solide, pailletée.',
  'deep.item.lightbringer': 'Porte-Lumière',
  'deep.item.lightbringer.perk': 'Légendaire. Brille. Bourdonne. Sûrement rien.',
  'deep.item.sunStaff': 'Bâton du Soleil',
  'deep.item.sunStaff.perk': 'Légendaire. Chaud au toucher. Très chaud.',
  'deep.item.potLid': 'Couvercle de casserole',
  'deep.item.potLid.perk': 'Ne casse jamais. Bloque à peine.',
  'deep.item.buckler': 'Rondache',
  'deep.item.buckler.perk': 'Petite et légère : parades plus faciles.',
  'deep.item.kite': 'Écu',
  'deep.item.kite.perk': 'Polyvalent et solide.',
  'deep.item.tower': 'Pavois',
  'deep.item.tower.perk': 'Absorbe beaucoup, mais parer est plus dur.',
  'deep.item.aegis': "Égide de l'Admin Sys",
  'deep.item.aegis.perk': 'Épique. Disponibilité 99,99 %.',
  'deep.item.small': 'Petite potion',
  'deep.item.small.perk': 'Goût cerise.',
  'deep.item.large': 'Grande potion',
  'deep.item.large.perk': 'Goût cerise et courage.',
  'deep.item.cola': 'Cherry Coke',
  'deep.item.cola.perk': 'La boisson préférée d’Ezra. Soigne beaucoup.',
  'deep.room.den': 'Le Repaire d’Ezra',
  'deep.room.den.line': 'Un canapé, une Game Boy, un chat qui dort. Personne n’est censé connaître cette pièce.',
  'deep.line.secret': 'Pièce secrète',
  'deep.nav.portal': 'Entrer dans le portail',
  'deep.nav.portalTo': 'Vers : {room}',
  'deep.nav.pet': 'Caresser le chat',
  'deep.nav.petDetail': '+{heal} PV · ronron',
  'deep.float.secret': 'PIÈCE SECRÈTE ! +{points}',
  'deep.float.purr': 'Rrrrr…',
  'deep.fairy.room.den': 'Le repaire d’Ezra ! Il se cache ici quand le build est rouge.',
  'deep.item.keycard': 'Badge du manager',
  'deep.item.keycard.perk': 'Ouvre la porte en fer.',
  'deep.noPotion': 'Pas de potion',
  'deep.map': 'Carte du donjon',
  'deep.room.unknown': 'Inexploré',
  'deep.room.street': 'Grand-Rue',
  'deep.room.h1': 'Grand-Rue · Portail',
  'deep.room.h2': 'Grand-Rue · Allée des flèches',
  'deep.room.h3': 'Grand-Rue · Carrefour',
  'deep.room.h4': 'Grand-Rue · Porte de fer',
  'deep.room.a1': 'Les Archives',
  'deep.room.a2': "L'Open Space",
  'deep.room.mb': 'Le Bureau du Manager',
  'deep.room.b1': 'La Salle Serveur',
  'deep.room.c1': 'La Salle de Pause',
  'deep.room.d1': 'La Descente',
  'deep.room.d2': 'La Crypte Inondée',
  'deep.room.d3': 'La Salle des Échos',
  'deep.room.lair': 'La Lumière',
  'deep.room.h1.line': 'Une longue rue de portes. Ça sent le vieux code.',
  'deep.room.h2.line': 'Les murs ont des trous. Les trous ont des flèches.',
  'deep.room.h3.line': 'Une porte bourdonne, avec une lueur de distributeur.',
  'deep.room.h4.line': 'Le bout de la rue. Une porte en fer avec lecteur de badge.',
  'deep.room.a1.line': 'Étagères poussiéreuses. Personne ne lit la doc.',
  'deep.room.a2.line': 'Des bureaux, des plantes, un clavier très bruyant.',
  'deep.room.mb.line': 'Poster motivant. Grand bureau. Plus grand ego.',
  'deep.room.b1.line': 'Des LED qui clignotent et un bourdonnement dans les dents.',
  'deep.room.c1.line': 'Distributeurs. Machine à café. Un coffre bizarrement brillant.',
  'deep.room.d1.line': "Des chaînes aux murs. L'air se refroidit.",
  'deep.room.d2.line': "De l'eau jusqu'aux genoux. Ça goutte. Ça attend.",
  'deep.room.d3.line': 'Feu violet et piliers. Tes pas te répondent.',
  'deep.room.lair.line': 'Une ampoule, qui se balance.',
  'deep.detail.weapon': '+{power} ATQ · {uses}/{max} coups',
  'deep.detail.shield': 'Absorbe {absorb} % · tient {uses}/{max} attaques',
  'deep.offline': 'Hors ligne : partie non enregistrée',
  'deep.detail.potion': '+{heal} PV',
  'deep.detail.potionCure': '+{heal} PV · soigne le poison',
  'deep.float.cured': 'GUÉRI !',
  'deep.fairy.poisoned': 'Du venin ! Ça brûle de plus en plus souvent. N’importe quelle potion le soigne.',
  'deep.fairy.poisoned.cryptic': 'Venin.',
  'deep.nav.eyebrow': 'On va où ?',
  'deep.nav.moveOn': 'Avancer ▸',
  'deep.nav.goBack': '◂ Reculer',
  'deep.nav.cleared': 'Déjà vidée',
  'deep.nav.unexplored': 'Inexploré',
  'deep.nav.enterDoor': 'Entrer',
  'deep.nav.exitDoor': 'Retour dans la rue',
  'deep.nav.goOn': 'Continuer ▸',
  'deep.nav.backTo': '◂ Revenir',
  'deep.nav.noReturn': 'Pas de retour',
  'deep.nav.open': 'Ouvrir le coffre brillant',
  'deep.nav.openDetail': "Qu'est-ce qui pourrait mal tourner ?",
  'deep.nav.coffee': 'Pause café',
  'deep.nav.coffeeDetail': '+{heal} PV · une fois',
  'deep.nav.take': 'Ramasser : {item}',
  'deep.nav.bagFull': 'Sac plein ({max} potions max)',
  'deep.nav.drink': 'Boire : {potion}',
  'deep.nav.locked': 'Porte en fer (fermée)',
  'deep.nav.needKeycard': 'Il faut le badge du manager',
  'deep.fairy.helloFriend': 'Psst… {name} ! Moi c’est Lumi. Tu as été adorable avec moi, alors je te soufflerai des astuces.',
  'deep.fairy.helloSulky': 'Ah. C’est toi. La personne qui a dit non. …Bon. Suis-moi.',
  'deep.fairy.friend.h1': 'Astuce : explore tout. Certains culs-de-sac valent le détour.',
  'deep.fairy.friend.a1': 'Retiens cette pièce. Reviens après le manager… ça scintille ici.',
  'deep.fairy.friend.mb': 'Il fait toujours pareil : cadenas, post-it, le gros hmpf, puis la réunion. Pare le hmpf !',
  'deep.fairy.friend.h4': 'Le manager a le badge. Une fois que tu l’as, les archives cachent un raccourci.',
  'deep.fairy.friend.d2': 'Cinq flèches ici, et deux arrivent par paires.',
  'deep.fairy.friend.d3': 'Le coffre ici mord. Frappe net.',
  'deep.fairy.friend.den': 'Le repaire d’Ezra ! Caresse le chat, crois-moi.',
  'deep.fairy.friend.drink': 'Tu as une sale tête. Bois quelque chose !',
  'deep.fairy.friend.lastRoom': 'La dernière salle est juste devant. Bois avant d’entrer… crois-moi.',
  'deep.fairy.friend.portal': 'Psst… l’air scintille ici maintenant. Un portail !',
  'deep.fairy.idle': 'Zzz… oh ! Tu hésites encore ?',
  'deep.fairy.locked': 'Fermé. Ce lecteur veut le badge du manager.',
  'deep.fairy.bagFull': "Sac plein. Bois-en une d'abord ?",
  'deep.fairy.keycard': 'Le badge ! Maintenant, la porte en fer…',
  'deep.fairy.worn': "Psst… {item} : plus que quelques coups. Les coups parfaits ne l'usent pas.",
  'deep.fairy.worn.hard': 'Psst… {item} : plus que quelques coups. Sache où trouver la suivante.',
  'deep.fairy.brokeWeapon': 'Cassé ! Retour au fidèle bâton. Lui, il ne casse jamais.',
  'deep.fairy.brokeShield': "Plus de bouclier ! Le couvercle fera l'affaire… à peu près.",
  'deep.fairy.loot': 'Astuce : laisse-le ici si le tien tient encore. Rien ne réapparaît, tu pourras revenir le chercher.',
  'deep.fairy.hordeDone': 'Tu as survécu à ÇA ? …enfin, bravo ! Prends un café.',
  'deep.fairy.reveal1': 'Psst… merci pour le badge.',
  'deep.fairy.reveal2': "Tu croyais vraiment que j'étais une fée ?",
  'deep.fairy.room.a1': 'Les archives. Personne ne les a ouvertes depuis 2009.',
  'deep.fairy.room.a2': "L'open space. Chut, y en a un en call.",
  'deep.fairy.room.mb': 'Aïe. Le bureau du manager.',
  'deep.fairy.room.b1': 'La salle serveur… si tu savais tout ce qui s’est passé par là…',
  'deep.fairy.room.c1': 'Oooh, un coffre qui brille ! Ouvre-le, ouvre-le !',
  'deep.fairy.room.h3': 'Un géant. Frappe net, ta lame te dira merci.',
  'deep.fairy.room.h4': 'Cette porte en fer, il faut un badge. Le manager a toujours le sien sur lui.',
  'deep.fairy.room.d1': "On descend. J'adore le noir.",
  'deep.fairy.room.d2': 'Attention aux murs. Et à tes pieds.',
  'deep.fairy.room.d3': 'On y est presque… la lumière est si proche.',
  'deep.tip.nav.eyebrow': 'Exploration',
  'deep.tip.nav.title': 'À toi de choisir',
  'deep.tip.nav.text': 'Les portes mènent aux salles. Une salle vidée le reste, et ce que tu laisses par terre y reste aussi. Planifie ta route : la carte montre où tu es passé.',
  'deep.tip.nav.short': 'Choisis une porte ou avance.',
  'deep.tip.strike.eyebrow': 'Attaque',
  'deep.tip.strike.title': 'Ici, le parfait est plus dur',
  'deep.tip.strike.text': "La zone dorée est minuscule. Un coup parfait fait triple dégâts ET n'use pas ton arme. Un coup faible l'use deux fois plus.",
  'deep.tip.strike.short': 'Or = parfait, zéro usure.',
  'deep.tip.strike.text.hard': 'La zone dorée est minuscule et file plus vite. Un coup parfait fait triple dégâts. En Difficile, chaque coup use ton arme, les faibles trois fois plus.',
  'deep.tip.strike.short.hard': 'Or = parfait. Tout s’use.',
  'deep.tip.strike.text.tryhard': 'La zone dorée est minuscule. Un coup parfait fait triple dégâts. En Try Hard, CHAQUE coup use ton arme, les faibles trois fois plus. Elle va casser : sache où trouver la suivante.',
  'deep.tip.defend.eyebrow': 'Défense',
  'deep.tip.defend.title': 'Un anneau = un coup',
  'deep.tip.defend.text': 'Chaque anneau qui se referme sur toi est un coup. Tape une fois par anneau, pile quand il touche le cercle blanc : PARADE = zéro dégât et ton prochain coup ×1,5. Un peu décalé = BLOCAGE, ta garde absorbe une partie. Trois anneaux ? Trois tapes, une pour chacun.',
  'deep.tip.defend.short': 'Une tape par anneau, quand il te touche.',
  'deep.tip.defend.text.hard': 'Chaque anneau qui se referme sur toi est un coup. Tape une fois par anneau, pile quand il touche le cercle blanc : PARADE = zéro dégât et ton prochain coup ×1,5. Un peu décalé = BLOCAGE. En Difficile, les anneaux s’effacent en approchant : sens le rythme.',
  'deep.tip.defend.short.hard': 'Les anneaux s’effacent près de toi. Garde le rythme.',
  'deep.tip.defend.text.tryhard': 'Chaque anneau qui se referme sur toi est un coup. Tape une fois par anneau quand il touche le cercle blanc : PARADE ou BLOCAGE. En Try Hard, les anneaux disparaissent juste avant l’impact. Compte le rythme.',
  'deep.tip.armor.eyebrow': 'Armure',
  'deep.tip.armor.title': 'Celui-là est blindé',
  'deep.tip.armor.text': "L'armure retire des dégâts à chaque coup. Les coups faibles l'égratignent à peine : vise l'or.",
  'deep.tip.armor.short': "Blindé : vise l'or.",
  'deep.tip.ghost.eyebrow': 'Fantôme',
  'deep.tip.ghost.title': 'Tu le vois… ou pas',
  'deep.tip.ghost.text': 'Les fantômes font disparaître le curseur par moments. Fie-toi à ton rythme.',
  'deep.tip.ghost.short': "Le curseur s'efface. Garde le rythme.",
  'deep.tip.arrows.eyebrow': 'Piège',
  'deep.tip.arrows.title': 'Flèches murales !',
  'deep.tip.arrows.text': 'Des flèches jaillissent du mur. Tape pour sauter pile quand une flèche t’atteint. Chaque flèche qui touche coûte {damage} PV.',
  'deep.tip.arrows.short': 'Tape pour sauter les flèches.',
  'deep.tip.horde.eyebrow': 'Horde',
  'deep.tip.horde.title': 'Ils sont quinze',
  'deep.tip.horde.text': "Ils arrivent des deux côtés, de plus en plus vite. Tape sur chaque temps quand ils t'atteignent. Spammer te fait brasser de l'air.",
  'deep.tip.horde.short': 'Tape chacun en rythme !',
  'deep.float.explore': 'NOUVELLE SALLE +{points}',
  'deep.float.elite': 'ÉLITE : {name} !',
  'deep.float.riposte': 'RIPOSTE ×1,5',
  'deep.float.broke': 'CRAC ! {item}',
  'deep.float.parry': 'PARADE !',
  'deep.float.block': 'BLOQUÉ',
  'deep.float.jump': 'ESQUIVÉ',
  'deep.float.jumpPerfect': 'ESQUIVE NETTE !',
  'deep.float.slash': 'TCHAC',
  'deep.float.slashPerfect': 'PARFAIT !',
  'deep.float.flail': "TU BRASSES DE L'AIR !",
  'deep.float.dusted': 'POUDRÉ ! Curseur plus rapide',
  'deep.float.keycard': 'BADGE !',
  'deep.float.itsATrap': "C'EST UN PIÈGE !",
  'deep.float.hordeClear': 'HORDE VAINCUE ! ({n})',
  'deep.float.hordePerfect': 'RYTHME PARFAIT !',
  'deep.float.untouched': 'INTOUCHABLE !',
  'deep.float.melon': 'MODE PASTÈQUE !',
  'deep.float.managerDown': 'RÉUNION TERMINÉE',
  'deep.float.dropped': 'Posé : {item}',
  'deep.float.left': 'Laissé ici : {item}',
  'deep.float.coffee': 'Aah, c’est bon.',
  'deep.announce.foe': '{name} apparaît avec {hp} PV.',
  'deep.foe.rat': 'Rat',
  'deep.foe.bat': 'Chauve-souris',
  'deep.foe.slime': 'Slime',
  'deep.foe.spider': 'Araignée géante',
  'deep.foe.ghost': 'Fantôme',
  'deep.foe.giant': 'Géant',
  'deep.foe.crab': 'Crabe démoniaque',
  'deep.foe.monk': 'Moine noir',
  'deep.foe.knight': 'Chevalier noir',
  'deep.foe.mimic': 'Faux coffre',
  'deep.foe.bug': 'Bug',
  'deep.foe.manager': 'LE MANAGER GROGNON',
  'deep.foe.manager.title': 'A une réunion à ce sujet',
  'deep.foe.moth': 'LE PREMIER BUG',
  'deep.foe.moth.title': 'Harvard Mark II · 9 sept. 1947',
  'deep.hint.arrows': 'Tape pour sauter !',
  'deep.hint.horde': 'Tape à chaque temps !',
  'deep.horde.title': 'LA HORDE !',
  'deep.horde.subtitle': 'Les portes sont verrouillées',
  'deep.potion.drink': '{potion} (+{heal})',
  'deep.tier.basic': 'Basique',
  'deep.tier.common': 'Commun',
  'deep.tier.rare': 'Rare',
  'deep.tier.epic': 'Épique',
  'deep.tier.legendary': 'Légendaire',
  'deep.loot.vsWeapon': 'Tu tiens : {item} · {detail}',
  'deep.loot.vsShield': 'Tu portes : {item} · {detail}',
  'deep.loot.bag': 'Sac : {n}/{max} potions',
  'deep.loot.takePotion': 'Prendre',
  'deep.loot.swap': 'Échanger',
  'deep.loot.take': 'Prendre',
  'deep.loot.leave': 'Laisser ici',
  'deep.loot.note': 'Ce que tu laisses reste ici. Reviens quand tu veux.',
  'deep.manager.speaker': 'LE MANAGER',
  'deep.manager.offstage': 'UNE VOIX, QUELQUE PART',
  'deep.powerCut': 'COUPURE DE COURANT !',
  'deep.fairy.powerCut': 'Qui a éteint la lumière ?! Suis les anneaux, eux ils brillent encore.',
  'deep.manager.intro': '{name}, on fait un point ?',
  'deep.manager.lock': 'Verrouille ton ordi !',
  'deep.manager.lastpass': 'Tous les mots de passe dans LastPass !',
  'deep.manager.meeting': 'Pas mal en réunion avec tout le monde.',
  'deep.manager.seeds': 'Y a comme un pépin !',
  'deep.manager.melon': "J'ai une tête comme une pastèque !",
  'deep.moth.speaker': 'LE PREMIER BUG',
  'deep.moth.intro': "En 1947, ils m'ont scotchée dans un cahier. Ce soir, c'est moi qui te débugge.",
  'deep.moth.dust': 'Poussière dans les yeux !',
  'deep.moth.spawn': 'Corrige un bug… il en revient deux !',
  'deep.moth.back': "Je t'ai manqué ?",
  'deep.moth.frenzy': 'Chez moi, ça marche !',
  'deep.logbook.aria': 'La page du cahier de bord avec le papillon scotché dessus : premier vrai cas de bug trouvé.',
  'deep.logbook.title': 'Bug corrigé.',
  'deep.killer.rat': 'un rat',
  'deep.killer.bat': 'une chauve-souris',
  'deep.killer.slime': 'un slime',
  'deep.killer.spider': 'une araignée géante',
  'deep.killer.ghost': 'un fantôme',
  'deep.killer.giant': 'un géant',
  'deep.killer.crab': 'un crabe démoniaque',
  'deep.killer.monk': 'un moine noir',
  'deep.killer.knight': 'un chevalier noir',
  'deep.killer.mimic': 'un faux coffre',
  'deep.killer.bug': 'un bug',
  'deep.killer.manager': 'le manager grognon',
  'deep.killer.moth': 'le premier bug',
  'deep.killer.horde': 'la horde',
  'deep.killer.arrow': 'une flèche murale',
  'deep.killer.poison': 'le venin d’araignée',
  'deep.killer.dungeon': 'le donjon',
  'deep.results.won': 'BUG CORRIGÉ',
  'deep.results.wonLine': '{name} a vaincu le Donjon des Profondeurs.',
  'deep.results.lostLine': "{name} s'est fait avoir par {killer} ({room}).",
  'deep.results.again': 'Nouveau héros',
  'deep.results.offline': "Hors ligne : tes {score} points n'ont pas été enregistrés.",
  'deep.results.rankLine': 'Tu serais {rank} sur le mur des légendes. Réessaie pour y graver ton nom !',
  'deep.results.qualified': 'Ton score entre sur le mur des légendes !',
  'deep.results.carved': '{initials} est gravé sur le mur des légendes !',
  'deep.line.strikes': 'Coups',
  'deep.line.combos': 'Combos parfaits',
  'deep.line.defense': 'Parades & blocages',
  'deep.line.dodges': 'Esquives',
  'deep.line.horde': 'Horde',
  'deep.line.kills': 'Victimes',
  'deep.line.flawless': 'Salles sans dégât',
  'deep.line.explore': 'Exploration',
  'deep.line.hp': 'PV restants',
  'deep.line.time': 'Bonus temps',
  'deep.wall': 'Le mur des légendes',
  'deep.secretLegend': 'a trouvé le passage secret',
  'deep.results.replay': 'Rejouer avec ce héros',
  'deep.logbook.skip': 'Clique ou appuie sur une touche',
  'deep.create.step.difficulty': 'Niveau',
  'deep.create.title.difficulty': 'Choisis ton défi',
  'deep.difficulty.normal': 'Normal',
  'deep.difficulty.hard': 'Difficile',
  'deep.difficulty.tryhard': 'Try Hard',
  'deep.difficulty.normal.perk': 'Le donjon tel qu’il a été construit. Il mord quand même.',
  'deep.difficulty.hard.perk': 'Les ennemis se renforcent à mesure que tu descends, les boss frappent fort, les potions soignent moins et chaque coup use ton arme.',
  'deep.difficulty.tryhard.perk': 'Ton équipement VA casser, le sac tient 2 potions, Lumi parle à peine. Prévois tes allers-retours.',
  'deep.difficulty.normal.short': 'Normal',
  'deep.difficulty.hard.short': 'Difficile',
  'deep.difficulty.tryhard.short': 'Try Hard',
  'deep.stat.foes': 'Ennemis',
  'deep.stat.bag': 'Sac',
  'deep.stat.score': 'Score',
  'deep.line.difficulty': 'Bonus de difficulté',
  'deep.fairy.helloTryhard': 'Try Hard ? Gonflé. Tu te débrouilles, {name}.',
  'deep.fairy.room.a1.cryptic': 'De la poussière. Et autre chose.',
  'deep.fairy.room.mb.cryptic': 'Lui.',
  'deep.fairy.room.b1.cryptic': 'Bzzt.',
  'deep.fairy.room.c1.cryptic': 'Ça brille…',
  'deep.fairy.room.h4.cryptic': 'Du fer.',
  'deep.fairy.room.d2.cryptic': 'Les murs ont des yeux.',
  'deep.fairy.room.d3.cryptic': 'Tout près.',
  'deep.fairy.room.den.cryptic': 'Chut.',
  'deep.fairy.powerCut.cryptic': 'Noir.',
  'deep.fairy.idle.cryptic': '…',
  'deep.fairy.locked.cryptic': 'Fermé.',
  'deep.fairy.bagFull.cryptic': 'Plein.',
  'deep.fairy.keycard.cryptic': 'Hm. Utile.',
  'deep.fairy.worn.cryptic': 'Ça craque…',
  'deep.fairy.brokeWeapon.cryptic': 'Crac.',
  'deep.fairy.brokeShield.cryptic': 'Crac.',
  'deep.fairy.hordeDone.cryptic': 'Tiens.',
  'deep.challenge': 'Peux-tu battre les {score} de {who} dans le Donjon des Profondeurs ? Demande à la fée.',
  'deep.wallEmpty': 'Aucune légende pour l’instant. La fée connaît le chemin.',
  'deep.share.top': '{initials} est sur le mur des légendes du Donjon des Profondeurs avec {score} pts. À toi : {url}',
  'deep.share.win': "J'ai vaincu le Donjon des Profondeurs avec {score} pts. Et toi ? {url}",
  'deep.share.death': "Le Donjon des Profondeurs m'a eu à {score} pts. Tu iras plus loin ? {url}",
  'fairy.psst': 'psst !',
  'fairy.question': 'Psst… et si on faisait un VRAI donjon ?',
  'fairy.yes': 'Oui !',
  'fairy.no': 'Non',
  'fairy.yesLine': 'Suis-moi !',
  'fairy.sad': '…bon. D’accord.',
  'fairy.label': 'Parler à la fée',
  'fairy.questionFriend': 'Psst… re-toi ! Un autre VRAI donjon ?',
  'fairy.questionSulky': 'Hmpf. La dernière fois, tu as dit non. …Un VRAI donjon, maintenant ?',
  'fairy.legends': '🏆 Le mur des légendes',
  'fairy.legendsLine': 'Seuls ceux qui en sont sortis y sont gravés.',
  'fairy.back': '◂ Retour',
  'fairy.konami': '+30 vies ? Pas dans CE donjon.',
  'fairy.name': 'Tu connais mon nom ?! …Personne ne dit jamais mon nom.',
};
