export const FEMININE_NAMES = ['Brunhilda', 'Merlina', 'Gwendolyn', 'Ingrid', 'Rowena', 'Elspeth', 'Morwenna', 'Agatha'];

export const EPITHETS_FR = [
  ['le Mouillé', 'la Mouillée'],
  ['le Moyennement Brave', 'la Moyennement Brave'],
  ['Sans Domicile Fixe', 'Sans Domicile Fixe'],
  ['le Surcaféiné', 'la Surcaféinée'],
  ['le Pas Prêt', 'la Pas Prête'],
  ['le Un Peu Perdu', 'la Un Peu Perdue'],
  ['le Bien Reposé', 'la Bien Reposée'],
  ['Qui a Sauté le Leg Day', 'Qui a Sauté le Leg Day'],
  ['le Semi-Légendaire', 'la Semi-Légendaire'],
  ['à la Sacoche à Goûter', 'à la Sacoche à Goûter'],
  ['le Facilement Effrayé', 'la Facilement Effrayée'],
  ["l'Invité Surprise", "l'Invitée Surprise"],
  ['Qui a Lu la Notice', 'Qui a Lu la Notice'],
  ["l'Optimiste", "l'Optimiste"],
  ['le Fraîchement Lavé', 'la Fraîchement Lavée'],
  ['le Presque Sûr', 'la Presque Sûre'],
  ['le Convenable', 'la Convenable'],
];

const EN = {
  skip: 'Skip',
  mute: 'Mute sound',
  unmute: 'Unmute sound',
  'boot.skip': 'tap to skip',
  'meter.label': 'Tap <kbd>Space</kbd> when the marker hits <b>gold</b>',
  'hint.chest': 'Tap to open the chest',
  'reveal.appears': 'A hero appears!',
  'reveal.legendary': 'A legendary hero appears!',
  'reveal.badge': 'LEGENDARY',
  'reveal.go': 'Enter the dungeon ▸',
  'reveal.tap': 'or tap anywhere',
  'stat.hp': 'HP',
  'stat.atk': 'ATK',
  'hud.hp': 'HP {hp}/{max}',
  'loot.rolled': 'You rolled a {face} · {rarity}',
  'loot.onward': 'Onward ▸',
  'loot.fine': 'Fine. Onward ▸',
  'loot.potionLine': 'Tastes like cherries and courage.',
  'loot.atk': '+{n} ATK',
  'loot.heal': '+{n} HP',
  'victory.cleared': 'Dungeon cleared!',
  'victory.time': 'TIME',
  'victory.strikes': 'STRIKES',
  'victory.crits': 'PERFECT',
  'victory.firstClear': 'First clear! Record set.',
  'victory.newRecord': 'New record!',
  'victory.best': 'Best: {rank} · {time}',
  'victory.claim': 'Claim your treasure ▸',
  'defeat.title': 'You died',
  'defeat.retry': 'New hero',
  'defeat.treasure': 'Show me the treasure anyway',
  'float.critical': 'PERFECT!',
  'float.combo': 'COMBO ×{n}!',
  'float.weak': 'WEAK',
  'float.enraged': 'ENRAGED!',
  'float.glug': 'Glug!',
  'float.mimic': 'MIMIC!',
  'float.mimicLoot': '…it coughs up loot anyway',
  'float.victory': 'VICTORY!',
  'float.wild': 'A wild {name}!',
  'float.flawless': 'FLAWLESS +{points}',
  'float.dodged': 'DODGED! +{points}',
  'float.grows': 'It grows!',
  'float.poison': 'Poisoned!',
  'float.fullHp': 'Full HP!',
  'float.atk': '+1 ATK',
  'float.double': 'NEXT HIT ×2',
  'float.early': 'Too early!',
  'float.saved': 'Saved for later',
  'announce.hero': '{name}, a {cls}, appears with {hp} HP and {atk} ATK.',
  'announce.strike': '{label}: {damage} damage. {foe} has {hp} HP left.',
  'announce.perfect': 'Perfect hit',
  'announce.hit': 'Hit',
  'announce.weak': 'Weak hit',
  'announce.foe': 'A wild {name} appears. {line}',
  'announce.potion': 'You drink the {potion} and heal {healed} HP.',
  'announce.enraged': '{name} is enraged!',
  'announce.roll': 'You rolled a {face}. {rarity} loot.',
  'announce.boss': '{name}, {title}, blocks the way with {hp} HP.',
  'announce.victory': 'Victory! Rank {rank} in {seconds} seconds.',
  'announce.dead': 'You died. {epitaph}',
  'treasure.eyebrow': 'The treasure',
  'treasure.tagline': 'Developer based in Annecy',
  'treasure.featured': 'Featured project',
  'treasure.pictoText': 'Free visual schedule builder for autism, ADHD & AAC. 11,500+ ARASAAC pictograms, OBF export, EN/FR/NL.',
  'treasure.visit': 'Visit picto.strikwerda.fr ↗',
  'treasure.findMe': 'Find me',
  'treasure.about': 'About this game',
  'treasure.aboutText': 'A remaster of my 2023 Java console school project, Dungeons & Dragons: random hero, d6 dice, chest loot and a dragon, rebuilt as a one-button pixel game.',
  'treasure.original': 'See the original on GitHub ↗',
  'treasure.source': 'Source code of this site ↗',
  'treasure.consoleCaption': '2023 · console version',
  'treasure.consoleEnlarge': 'Enlarge the 2023 console version screenshot',
  'treasure.play': 'Play the game',
  'treasure.playAgain': 'Play again',
  'treasure.real': 'or… ⚔ ENTER THE REAL DUNGEON',
  'treasure.realSub': 'only 5 names fit on the wall',
  'treasure.credits': 'Sprites: Tiny Dungeon by Kenney (CC0) · Font: Pixelify Sans (OFL) · © 2026 Ezra',
  'treasure.close': 'Close',
  'badge.won': '{hero} slew {dragon} · Rank {rank} · {time}',
  'badge.lost': '{hero} fell in the dungeon. The treasure is yours anyway.',
  'badge.best': 'Your best run: Rank {rank} · {time}',
  'badge.real': '{hero} scored {score} pts in the real dungeon',
  'challenge.banner': "Can you beat {who}'s {score}?",
  'challenge.someone': 'this',
  'class.warrior': 'Warrior',
  'class.wizard': 'Wizard',
  'rarity.common': 'Common',
  'rarity.uncommon': 'Uncommon',
  'rarity.rare': 'Rare',
  'rarity.epic': 'Epic',
  'rarity.legendary': 'Legendary',
  'rank.S': 'Flawless. Bards will sing of this.',
  'rank.A': 'Heroic. Mostly unsinged.',
  'rank.B': 'Victory! A little crispy.',
  'rank.C': 'You won. Somehow.',
  'item.woodenStick.name': 'Wooden Stick',
  'item.woodenStick.line': 'The chest looks smug.',
  'item.morningStar.name': 'Morning Star',
  'item.morningStar.line': 'Spiky. Very much a morning person.',
  'item.lightbringer.name': 'Lightbringer',
  'item.lightbringer.line': 'Glows. Hums. Probably fine.',
  'item.lightningBolt.name': 'Lightning Bolt',
  'item.lightningBolt.line': 'Crackles with ambition.',
  'item.fireball.name': 'Fireball',
  'item.fireball.line': 'Warm to the touch. Very warm.',
  'potion.small.name': 'Small Potion',
  'potion.large.name': 'Large Potion',
  'foe.giant.name': 'Giant',
  'foe.giant.line': 'One eye. Zero manners.',
  'foe.slime.name': 'Slime',
  'foe.slime.line': 'It wobbles menacingly.',
  'foe.spider.name': 'Giant Spider',
  'foe.spider.line': 'Too many legs. Way too many.',
  'foe.ghost.name': 'Ghost',
  'foe.ghost.line': 'Boo. It is trying its best.',
  'foe.bat.name': 'Bat',
  'foe.bat.line': 'Screams in ultrasound.',
  'foe.rat.name': 'Rat',
  'foe.rat.line': 'Chewed through the Wi-Fi cable.',
  'foe.crab.name': 'Crab Demon',
  'foe.crab.line': 'Pinches first, asks later.',
  'foe.monk.name': 'Dark Monk',
  'foe.monk.line': 'Took a vow of violence.',
  'foe.scopeCreep.name': 'SCOPE CREEP',
  'foe.scopeCreep.title': 'It only gets bigger',
  'foe.monolith.name': 'THE LEGACY MONOLITH',
  'foe.monolith.title': 'Too big for this screen',
  'dragon.title.0': 'Breaker of Builds',
  'dragon.title.1': 'Devourer of Deadlines',
  'dragon.title.2': 'Keeper of Legacy Code',
  'dragon.title.3': 'the Friday Deploy',
  'dragon.title.4': 'Merge Conflict Incarnate',
  'dragon.title.5': 'Hoarder of Tech Debt',
  'dragon.title.6': 'Scourge of Production',
  'dragon.title.7': 'Eater of Semicolons',
  'dragon.title.8': 'Scourge of the North',
  'dragon.title.9': 'Last of the Ember Kings',
  'epitaph.0': 'Here lies {name}. Brought a {item} to a dragon fight.',
  'epitaph.1': '{name} was toast. Lightly buttered.',
  'epitaph.2': '{name} fought bravely. The dragon fought better.',
  'epitaph.3': 'Crispy on the outside. {name} on the inside.',
  'epitaph.4': '{name}: gone, but not forgotten. Well, mostly forgotten.',
  'epitaph.5': 'Here lies {name}. Respawning shortly.',
  'real.title': 'THE REAL DUNGEON',
  'real.subtitle': 'Score counts. Only 5 names fit on the wall.',
  'real.score': 'SCORE',
  'real.room': 'ROOM {n}/{total}',
  'real.heroEyebrow': 'Choose your hero',
  'real.continue': 'Continue with {name}',
  'real.continueDetail': '{cls} · {item} · {potions}',
  'real.potionsCount': '{n} potions',
  'real.potionsNone': 'no potion',
  'real.potionsOne': '1 potion',
  'real.newHero': 'Roll a new hero',
  'real.newHeroDetail': 'Random class, Wooden Stick, no potion',
  'real.potionEyebrow': 'Your HP is critical!',
  'real.potionQuestion': 'Drink a potion?',
  'real.drink': 'Drink',
  'real.save': 'Save it',
  'real.double': 'DOUBLE SHOT',
  'real.doubleShot': 'DOUBLE SHOT!',
  'real.dodge': 'DODGE!',
  'real.trap': "It's a trap!",
  'real.weakSpot': 'WEAK SPOT!',
  'real.aimHint': 'Tap when the crosshair is on the eye',
  'real.bullseye': 'BULLSEYE!',
  'real.close': 'CLOSE!',
  'real.head': 'Clonk.',
  'real.miss': 'MISS',
  'real.genieEyebrow': 'The genie asks',
  'real.genieRight': 'Correct!',
  'real.genieWrong': 'Wrong! The genie laughs.',
  'real.genieGoed': 'GOED! 👍',
  'real.genieAll': 'Correct! …but so were all the others!',
  'real.genieHired': 'Excellent taste.',
  'real.geniePoison': 'Wrong answer. Enjoy the arrow.',
  'real.reward.potion': 'Reward: a Large Potion',
  'real.reward.heal': 'Reward: +6 HP',
  'real.reward.atk': 'Reward: +1 ATK',
  'real.reward.points': 'Reward: +500 points',
  'real.fast': 'Fast answer +250',
  'real.victory': 'THE MONOLITH FALLS!',
  'real.gameOver': 'GAME OVER',
  'real.killedBy': 'Defeated by {name}',
  'real.checking': 'Counting your score…',
  'real.total': 'TOTAL',
  'real.line.strikes': 'Strikes',
  'real.line.combos': 'Perfect combos',
  'real.line.weakSpot': 'Weak spot',
  'real.line.dodges': 'Dodges',
  'real.line.genie': 'Genie',
  'real.line.kills': 'Kills',
  'real.line.flawless': 'Flawless rooms',
  'real.line.hp': 'HP left',
  'real.line.time': 'Time bonus',
  'real.leaderboard': 'The wall',
  'real.emptyBoard': 'Nobody yet. Be the first name on the wall.',
  'real.qualified': 'Your name goes on the wall!',
  'real.initialsHint': 'Tap a letter to change it · hold to scroll',
  'real.initialsSave': 'Carve it ▸',
  'real.initialsTaken': 'That name is not allowed. Try another.',
  'real.share': 'Share your result',
  'real.shareNative': 'Share…',
  'real.copy': 'Copy',
  'real.copied': 'Copied!',
  'real.again': 'Try again',
  'real.back': 'Back to the treasure',
  'real.offline': 'The dungeon gate is stuck (server offline). Try again later.',
  'real.submitFailed': "Couldn't reach the wall. Your score: {score}.",
  'real.bot': 'Sorry… only humans can play 🤖',
  'real.botText': 'That run was a little too perfect. Real hands wobble.',
  'real.source': 'How it works: source on GitHub ↗',
  'real.dodgeHint': 'Tap the moment the red ! flashes',
  'real.victoryLine': '{name} took down the Monolith. Legend.',
  'real.trapTitle': 'TAP TO DODGE THE POISON ARROWS!',
  'real.trapText': 'When the red ! flashes on the wall, tap to jump over the arrow.',
  'real.ready': 'Ready!',
  'real.tapNow': 'TAP!',
  'real.aimTitle': 'WEAK SPOT!',
  'real.aimText': 'A crosshair drifts over its face. Tap when it is on the red eye. One shot!',
  'boss.speaker': 'THE MONOLITH',
  'boss.intro1': 'WHO DARES TOUCH THE LEGACY CODE?',
  'boss.intro2': "I've been in production since 1998, {name}. Nobody knows how I work. Not even me.",
  'boss.enrage': "DON'T TOUCH THAT! It's load-bearing!",
  'boss.death': 'Fatal error… core dumped…',
  'treasure.scrollHint': 'Scroll down to enter the real dungeon',
  'lang.title': 'Language',
  'lang.switch': 'Version française',
  'real.reward.healN': 'Reward: +{n} HP',
  'real.wallArrow': 'A wall arrow',
  'real.initialsUp': 'Next letter',
  'real.initialsDown': 'Previous letter',
  'real.initialsFailed': "Couldn't reach the wall. Try again.",
  'real.initialsLate': 'Too late, the wall filled up. Your score still counts.',
  'real.carved': '{initials} is on the wall!',
  'share.win': "⚔️ I beat THE LEGACY MONOLITH in Ezra's pixel dungeon: {score} pts, {perfects} perfect hits. Can you do better? {url}",
  'share.top': "🏆 I'm on the wall as {initials} in Ezra's pixel dungeon: {score} pts. Can you knock me off? {url}",
  'share.death': "💀 {killer} ate my hero at {score} pts in Ezra's pixel dungeon. Avenge me: {url}",
  'q.hire.text': 'Would you hire Ezra as a developer on your team?',
  'q.hire.yes': 'Yes, obviously',
  'q.hire.no': 'No',
  'q.nationality.text': "What is Ezra's nationality?",
  'q.nationality.nl': 'Dutch',
  'q.nationality.be': 'Belgian',
  'q.nationality.de': 'German',
  'q.nationality.fr': 'French',
  'q.drink.text': "What's Ezra's favourite drink?",
  'q.drink.cherryCola': 'Cherry Coke',
  'q.drink.beer': 'Beer',
  'q.drink.wine': 'Wine',
  'q.drink.cocktail': 'Cocktail',
  'q.console.text': 'Which console does Ezra play the most?',
  'q.console.switch': 'Switch',
  'q.console.playstation': 'PlayStation',
  'q.console.xbox': 'Xbox',
  'q.console.gameboy': 'Game Boy',
  'q.pet.text': 'What pet does Ezra have?',
  'q.pet.cat': 'Cat',
  'q.pet.dog': 'Dog',
  'q.pet.dragon': 'Dragon',
  'q.pet.fish': 'Fish',
  'q.os.text': "Ezra's favourite OS?",
  'q.os.linux': 'Linux',
  'q.os.macos': 'macOS',
  'q.os.windows': 'Windows',
  'q.skills.text': 'Ezra is proficient in…',
  'q.volunteer.text': 'In his spare time, Ezra volunteers as a…',
  'q.volunteer.firefighter': 'Firefighter',
  'q.volunteer.gendarme': 'Gendarme',
  'q.volunteer.duck': 'Rubber-duck lifeguard',
};

const FR = {
  skip: 'Passer',
  mute: 'Couper le son',
  unmute: 'Activer le son',
  'boot.skip': 'touche pour passer',
  'meter.label': "Tape <kbd>Espace</kbd> quand le curseur est sur l'<b>or</b>",
  'hint.chest': 'Touche pour ouvrir le coffre',
  'reveal.appears': 'Un héros apparaît !',
  'reveal.legendary': 'Un héros légendaire apparaît !',
  'reveal.badge': 'LÉGENDAIRE',
  'reveal.go': 'Entrer dans le donjon ▸',
  'reveal.tap': "ou touche n'importe où",
  'stat.hp': 'PV',
  'stat.atk': 'ATQ',
  'hud.hp': 'PV {hp}/{max}',
  'loot.rolled': 'Tu as fait {face} · {rarity}',
  'loot.onward': 'En avant ▸',
  'loot.fine': 'Bon. En avant ▸',
  'loot.potionLine': 'Goût cerise et courage.',
  'loot.atk': '+{n} ATQ',
  'loot.heal': '+{n} PV',
  'victory.cleared': 'Donjon terminé !',
  'victory.time': 'TEMPS',
  'victory.strikes': 'COUPS',
  'victory.crits': 'PARFAITS',
  'victory.firstClear': 'Première victoire ! Record établi.',
  'victory.newRecord': 'Nouveau record !',
  'victory.best': 'Record : {rank} · {time}',
  'victory.claim': 'Réclamer le trésor ▸',
  'defeat.title': 'Tu es mort',
  'defeat.retry': 'Nouveau héros',
  'defeat.treasure': 'Montre-moi quand même le trésor',
  'float.critical': 'PARFAIT !',
  'float.combo': 'COMBO ×{n} !',
  'float.weak': 'FAIBLE',
  'float.enraged': 'ENRAGÉ !',
  'float.glug': 'Glou !',
  'float.mimic': 'MIMIQUE !',
  'float.mimicLoot': '…il crache quand même du butin',
  'float.victory': 'VICTOIRE !',
  'float.wild': '{name} surgit !',
  'float.flawless': 'SANS UNE ÉGRATIGNURE +{points}',
  'float.dodged': 'ESQUIVÉ ! +{points}',
  'float.grows': 'Ça grossit !',
  'float.poison': 'Empoisonné !',
  'float.fullHp': 'PV au max !',
  'float.atk': '+1 ATQ',
  'float.double': 'PROCHAIN COUP ×2',
  'float.early': 'Trop tôt !',
  'float.saved': 'Gardée pour plus tard',
  'announce.hero': '{name}, {cls}, apparaît avec {hp} PV et {atk} ATQ.',
  'announce.strike': '{label} : {damage} dégâts. Il reste {hp} PV à {foe}.',
  'announce.perfect': 'Coup parfait',
  'announce.hit': 'Touché',
  'announce.weak': 'Coup faible',
  'announce.foe': '{name} surgit. {line}',
  'announce.potion': 'Tu bois la {potion} et récupères {healed} PV.',
  'announce.enraged': '{name} est enragé !',
  'announce.roll': 'Tu as fait {face}. Butin {rarity}.',
  'announce.boss': '{name}, {title}, bloque le passage avec {hp} PV.',
  'announce.victory': 'Victoire ! Rang {rank} en {seconds} secondes.',
  'announce.dead': 'Tu es mort. {epitaph}',
  'treasure.eyebrow': 'Le trésor',
  'treasure.tagline': 'Développeur basé à Annecy',
  'treasure.featured': 'Projet phare',
  'treasure.pictoText': "Créateur gratuit de plannings visuels pour l'autisme, le TDAH et la CAA. 11 500+ pictogrammes ARASAAC, export OBF, EN/FR/NL.",
  'treasure.visit': 'Visiter picto.strikwerda.fr ↗',
  'treasure.findMe': 'Me trouver',
  'treasure.about': 'À propos du jeu',
  'treasure.aboutText': "Un remaster de mon projet d'école de 2023 en Java, en console : Donjons & Dragons. Héros aléatoire, dé à six faces, butin dans un coffre et un dragon, reconstruit en jeu pixel à un seul bouton.",
  'treasure.original': "Voir l'original sur GitHub ↗",
  'treasure.source': 'Code source de ce site ↗',
  'treasure.consoleCaption': '2023 · version console',
  'treasure.consoleEnlarge': "Agrandir la capture d'écran de la version console de 2023",
  'treasure.play': 'Jouer',
  'treasure.playAgain': 'Rejouer',
  'treasure.real': 'ou… ⚔ ENTRER DANS LE VRAI DONJON',
  'treasure.realSub': 'seuls 5 noms tiennent sur le mur',
  'treasure.credits': 'Sprites : Tiny Dungeon par Kenney (CC0) · Police : Pixelify Sans (OFL) · © 2026 Ezra',
  'treasure.close': 'Fermer',
  'badge.won': '{hero} a terrassé {dragon} · Rang {rank} · {time}',
  'badge.lost': '{hero} a péri dans le donjon. Le trésor est à toi quand même.',
  'badge.best': 'Ta meilleure partie : Rang {rank} · {time}',
  'badge.real': '{hero} a marqué {score} pts dans le vrai donjon',
  'challenge.banner': 'Peux-tu battre les {score} de {who} ?',
  'challenge.someone': 'ce joueur',
  'class.warrior': 'Guerrier',
  'class.wizard': 'Magicien',
  'rarity.common': 'Commun',
  'rarity.uncommon': 'Peu commun',
  'rarity.rare': 'Rare',
  'rarity.epic': 'Épique',
  'rarity.legendary': 'Légendaire',
  'rank.S': 'Parfait. Les bardes en chanteront.',
  'rank.A': 'Héroïque. À peine roussi.',
  'rank.B': 'Victoire ! Un peu grillé.',
  'rank.C': "Gagné. Ne demande pas comment.",
  'item.woodenStick.name': 'Bâton en bois',
  'item.woodenStick.line': "Le coffre a l'air très content de lui.",
  'item.morningStar.name': 'Étoile du matin',
  'item.morningStar.line': 'Pointue. Clairement du matin.',
  'item.lightbringer.name': 'Porte-Lumière',
  'item.lightbringer.line': 'Ça brille. Ça bourdonne. Sûrement rien.',
  'item.lightningBolt.name': 'Éclair',
  'item.lightningBolt.line': "Crépite d'ambition.",
  'item.fireball.name': 'Boule de feu',
  'item.fireball.line': 'Chaud au toucher. Très chaud.',
  'potion.small.name': 'Petite potion',
  'potion.large.name': 'Grande potion',
  'foe.giant.name': 'Géant',
  'foe.giant.line': 'Un œil. Zéro manières.',
  'foe.slime.name': 'Gelée',
  'foe.slime.line': 'Elle tremblote de façon menaçante.',
  'foe.spider.name': 'Araignée géante',
  'foe.spider.line': 'Trop de pattes. Vraiment trop.',
  'foe.ghost.name': 'Fantôme',
  'foe.ghost.line': 'Bouh. Il fait de son mieux.',
  'foe.bat.name': 'Chauve-souris',
  'foe.bat.line': 'Hurle en ultrasons.',
  'foe.rat.name': 'Rat',
  'foe.rat.line': 'A rongé le câble du Wi-Fi.',
  'foe.crab.name': 'Démon-crabe',
  'foe.crab.line': "Pince d'abord, discute après.",
  'foe.monk.name': 'Moine noir',
  'foe.monk.line': 'A fait vœu de violence.',
  'foe.scopeCreep.name': 'SCOPE CREEP',
  'foe.scopeCreep.title': 'Ça ne fait que grossir',
  'foe.monolith.name': 'LE MONOLITHE LEGACY',
  'foe.monolith.title': 'Trop grand pour cet écran',
  'dragon.title.0': 'Briseur de Builds',
  'dragon.title.1': 'Dévoreur de Deadlines',
  'dragon.title.2': 'Gardien du Code Legacy',
  'dragon.title.3': 'le Déploiement du Vendredi',
  'dragon.title.4': 'Conflit de Merge Incarné',
  'dragon.title.5': 'Amasseur de Dette Technique',
  'dragon.title.6': 'Fléau de la Prod',
  'dragon.title.7': 'Mangeur de Points-Virgules',
  'dragon.title.8': 'Fléau du Nord',
  'dragon.title.9': 'Dernier des Rois de Braise',
  'epitaph.0': "Ci-gît {name}. Venu·e au combat de dragon avec {item}.",
  'epitaph.1': '{name} a fini en toast. Légèrement beurré.',
  'epitaph.2': '{name} a combattu vaillamment. Le dragon, mieux.',
  'epitaph.3': "Croustillant à l'extérieur. {name} à l'intérieur.",
  'epitaph.4': '{name} : parti·e, mais pas oublié·e. Enfin, presque.',
  'epitaph.5': 'Ci-gît {name}. Réapparition imminente.',
  'real.title': 'LE VRAI DONJON',
  'real.subtitle': 'Le score compte. Seuls 5 noms tiennent sur le mur.',
  'real.score': 'SCORE',
  'real.room': 'SALLE {n}/{total}',
  'real.heroEyebrow': 'Choisis ton héros',
  'real.continue': 'Continuer avec {name}',
  'real.continueDetail': '{cls} · {item} · {potions}',
  'real.potionsCount': '{n} potions',
  'real.potionsNone': 'pas de potion',
  'real.potionsOne': '1 potion',
  'real.newHero': 'Tirer un nouveau héros',
  'real.newHeroDetail': 'Classe au hasard, bâton en bois, pas de potion',
  'real.potionEyebrow': 'Tes PV sont au plus bas !',
  'real.potionQuestion': 'Boire une potion ?',
  'real.drink': 'Boire',
  'real.save': 'La garder',
  'real.double': 'CUL SEC ×2',
  'real.doubleShot': 'CUL SEC ×2 !',
  'real.dodge': 'ESQUIVE !',
  'real.trap': "C'est un piège !",
  'real.weakSpot': 'POINT FAIBLE !',
  'real.aimHint': "Touche quand le viseur est sur l'œil",
  'real.bullseye': 'EN PLEIN DANS LE MILLE !',
  'real.close': 'PRESQUE !',
  'real.head': 'Clonk.',
  'real.miss': 'RATÉ',
  'real.genieEyebrow': 'Le génie demande',
  'real.genieRight': 'Bonne réponse !',
  'real.genieWrong': 'Faux ! Le génie se marre.',
  'real.genieGoed': 'GOED! 👍',
  'real.genieAll': 'Bonne réponse ! …mais toutes les autres aussi !',
  'real.genieHired': 'Excellent choix.',
  'real.geniePoison': 'Mauvaise réponse. Profite de la flèche.',
  'real.reward.potion': 'Récompense : une grande potion',
  'real.reward.heal': 'Récompense : +6 PV',
  'real.reward.atk': 'Récompense : +1 ATQ',
  'real.reward.points': 'Récompense : +500 points',
  'real.fast': 'Réponse rapide +250',
  'real.victory': 'LE MONOLITHE TOMBE !',
  'real.gameOver': 'GAME OVER',
  'real.killedBy': 'Vaincu par {name}',
  'real.checking': 'On compte ton score…',
  'real.total': 'TOTAL',
  'real.line.strikes': 'Coups',
  'real.line.combos': 'Combos parfaits',
  'real.line.weakSpot': 'Point faible',
  'real.line.dodges': 'Esquives',
  'real.line.genie': 'Génie',
  'real.line.kills': 'Monstres vaincus',
  'real.line.flawless': 'Salles sans dégâts',
  'real.line.hp': 'PV restants',
  'real.line.time': 'Bonus de temps',
  'real.leaderboard': 'Le mur',
  'real.emptyBoard': 'Personne encore. Sois le premier nom sur le mur.',
  'real.qualified': 'Ton nom va sur le mur !',
  'real.initialsHint': 'Touche une lettre pour la changer · maintiens pour défiler',
  'real.initialsSave': 'Graver ▸',
  'real.initialsTaken': "Ce nom n'est pas autorisé. Essaie-en un autre.",
  'real.share': 'Partage ton résultat',
  'real.shareNative': 'Partager…',
  'real.copy': 'Copier',
  'real.copied': 'Copié !',
  'real.again': 'Réessayer',
  'real.back': 'Retour au trésor',
  'real.offline': 'La porte du donjon est coincée (serveur hors ligne). Réessaie plus tard.',
  'real.submitFailed': "Impossible d'atteindre le mur. Ton score : {score}.",
  'real.bot': 'Désolé… seuls les humains peuvent jouer 🤖',
  'real.botText': 'Cette partie était un peu trop parfaite. Les vraies mains tremblent.',
  'real.source': 'Comment ça marche : le code sur GitHub ↗',
  'real.dodgeHint': 'Touche dès que le ! rouge clignote',
  'real.victoryLine': '{name} a terrassé le Monolithe. Légendaire.',
  'real.trapTitle': 'TOUCHE POUR ESQUIVER LES FLÈCHES EMPOISONNÉES !',
  'real.trapText': "Quand le ! rouge clignote sur le mur, touche l'écran pour sauter par-dessus la flèche.",
  'real.ready': 'Prêt !',
  'real.tapNow': 'TOUCHE !',
  'real.aimTitle': 'POINT FAIBLE !',
  'real.aimText': "Un viseur se balade sur son visage. Touche quand il est sur l'œil rouge. Un seul tir !",
  'boss.speaker': 'LE MONOLITHE',
  'boss.intro1': 'QUI OSE TOUCHER AU CODE LEGACY ?',
  'boss.intro2': 'Je tourne en prod depuis 1998, {name}. Personne ne sait comment je marche. Même pas moi.',
  'boss.enrage': 'NE TOUCHE PAS À ÇA ! Ça tient tout le reste !',
  'boss.death': 'Erreur fatale… core dumped…',
  'treasure.scrollHint': 'Descends pour entrer dans le vrai donjon',
  'lang.title': 'Langue',
  'lang.switch': 'English version',
  'real.reward.healN': 'Récompense : +{n} PV',
  'real.wallArrow': 'Une flèche du mur',
  'real.initialsUp': 'Lettre suivante',
  'real.initialsDown': 'Lettre précédente',
  'real.initialsFailed': 'Impossible de joindre le mur. Réessaie.',
  'real.initialsLate': 'Trop tard, le mur est plein. Ton score compte quand même.',
  'real.carved': '{initials} est sur le mur !',
  'share.win': "⚔️ J'ai battu LE MONOLITHE LEGACY dans le donjon pixel d'Ezra : {score} pts, {perfects} coups parfaits. Tu fais mieux ? {url}",
  'share.top': "🏆 Je suis sur le mur sous le nom {initials} dans le donjon pixel d'Ezra : {score} pts. Tu me détrônes ? {url}",
  'share.death': "💀 {killer} a mangé mon héros à {score} pts dans le donjon pixel d'Ezra. Venge-moi : {url}",
  'q.hire.text': 'Embaucherais-tu Ezra comme développeur dans ton équipe ?',
  'q.hire.yes': 'Oui, évidemment',
  'q.hire.no': 'Non',
  'q.nationality.text': 'Quelle est la nationalité d’Ezra ?',
  'q.nationality.nl': 'Néerlandaise',
  'q.nationality.be': 'Belge',
  'q.nationality.de': 'Allemande',
  'q.nationality.fr': 'Française',
  'q.drink.text': 'Quelle est la boisson préférée d’Ezra ?',
  'q.drink.cherryCola': 'Coca Cherry',
  'q.drink.beer': 'Bière',
  'q.drink.wine': 'Vin',
  'q.drink.cocktail': 'Cocktail',
  'q.console.text': 'À quelle console Ezra joue-t-il le plus ?',
  'q.console.switch': 'Switch',
  'q.console.playstation': 'PlayStation',
  'q.console.xbox': 'Xbox',
  'q.console.gameboy': 'Game Boy',
  'q.pet.text': 'Quel animal Ezra a-t-il ?',
  'q.pet.cat': 'Chat',
  'q.pet.dog': 'Chien',
  'q.pet.dragon': 'Dragon',
  'q.pet.fish': 'Poisson',
  'q.os.text': 'L’OS préféré d’Ezra ?',
  'q.os.linux': 'Linux',
  'q.os.macos': 'macOS',
  'q.os.windows': 'Windows',
  'q.skills.text': 'Ezra maîtrise…',
  'q.volunteer.text': 'Pendant son temps libre, Ezra est volontaire comme…',
  'q.volunteer.firefighter': 'Pompier',
  'q.volunteer.gendarme': 'Gendarme',
  'q.volunteer.duck': 'Maître-nageur pour canards en plastique',
};

export const STRINGS = { en: EN, fr: FR };
